name: Lint Pull Request

# Déclenchement du workflow lorsqu'une Pull Request est ouverte ou synchronisée
on:
  pull_request:
    branches:
      - main
      - Lint

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # Vérification du code (Check out the repo)
      - name: Checkout code
        uses: actions/checkout@v4

      # Installer Node.js (par exemple, si vous utilisez ESLint)
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      # Installer les dépendances
      - name: Install dependencies
        run: npm ci

      # Lancer linter (par exemple avec ESLint)
      - name: Run ESLint
        run: npm run lint